### GET actions
GET http://localhost:3000/actions

### GET action by ID
GET http://localhost:3000/actions/685c8c9f98d3b09861265c9c

### POST action
POST http://localhost:3000/actions
Content-Type: application/json

{
  "title": "Usar lamparas LED bajo consumo",
  "description": "",
  "carbon": 2,
  "category": "energía",
  "agus": 123
}

### UPDATE action
PUT http://localhost:3000/actions/685d78b1b415422b12e560b7
Content-Type: application/json

{
  "description": "Una descripción actualizada."
}

### DELETE action
DELETE http://localhost:3000/actions/685f350a4ee599634c5082097