### GET actions
GET http://localhost:3000/actions

### GET action by ID
GET http://localhost:3000/actions/685a1d1eeefad9aca75e23a5

### POST action
POST http://localhost:3000/actions
Content-Type: application/json

{
  "title": "Usar lamparas LED bajo consumo",
  "description": "",
  "carbon": 2,
  "category": "energía"
}

### UPDATE action
PUT http://localhost:3000/actions/685af933dc81f66cda1613a9
Content-Type: application/json

{
  "description": "new"
}

### DELETE action
DELETE http://localhost:3000/actions/685afa6aff6d24eaa062544c