### GET categories
GET http://localhost:3000/categories

### GET category by ID
GET http://localhost:3000/categories/6866bd0c9af8b836391fcd0e

### POST create category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Energía"
}

### PUT update category
PUT http://localhost:3000/categories/6866bcd79af8b836391fcd06
Content-Type: application/json

{
  "name": "Updated Category"
}

### DELETE delete category
DELETE http://localhost:3000/categories/6866bcd79af8b836391fcd06
