### GET actions
GET http://localhost:3000/actions

### GET actions BY category
GET http://localhost:3000/actions?category=energia

### GET action by ID
GET http://localhost:3000/actions/19b48c77-5564-11f0-b7f9-7085c2cd2972

### POST action
POST http://localhost:3000/actions
Content-Type: application/json

{
  "title": "Juntar agua de lluvia para regar",
  "description": "",
  "carbon": 2,
  "categoryId": "8b6b5625-555e-11f0-b7f9-7085c2cd2972"
}

### UPDATE action
PUT http://localhost:3000/actions/4b0e5e3e-5565-11f0-b7f9-7085c2cd2972
Content-Type: application/json

{
  "description": "Una descripción actualizada."
}

### DELETE action
DELETE http://localhost:3000/actions/31a641e5-5564-11f0-b7f9-7085c2cd2972