### GET categories
GET http://localhost:3000/categories

### GET category by ID
GET http://localhost:3000/categories/dd3bf433-5b78-11f0-a4d8-7085c2cd2972

### POST create category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Nueva categoría"
}

### PUT update category
PUT http://localhost:3000/categories/dd3bf433-5b78-11f0-a4d8-7085c2cd2972
Content-Type: application/json

{
  "name": "Updated Category"
}

### DELETE delete category
DELETE http://localhost:3000/categories/dd3bf433-5b78-11f0-a4d8-7085c2cd2972
